cluster.name: "{{ cluster_name }}"

node.name: "{{ inventory_hostname }}"

network.host: 0.0.0.0
network.publish_host: {{ hostvars[inventory_hostname]['ansible_private_host'] }}

http.port: 9200
bootstrap.memory_lock: true
discovery.seed_providers: file

node.roles: [{{ hostvars[inventory_hostname]['roles'] }}]
script.painless.regex.enabled: true
action.auto_create_index: ".security,.monitoring*,.watches,.triggered_watches,.watcher-history*,.ml*"
